version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tg-bono-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=tg-bono
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - tg-bono-network

  mongo-init:
    image: mongo:7.0
    depends_on:
      - mongodb
    restart: "no"
    command: >
      mongosh --host mongodb:27017 --eval "
      rs.initiate({
        _id: 'rs0',
        members: [
          { _id: 0, host: 'mongodb:27017' }
        ]
      })
      "
    networks:
      - tg-bono-network

volumes:
  mongodb_data:

networks:
  tg-bono-network:
    driver: bridge
